### ISSUE TITLE
Suggestion - streaming?

### ISSUE THREAD

**Issue by Dycool** [techchrism/valorant-autorecord#1]
Instead of starting a recording, maybe starting a stream to youtube or something with all the metadata (private stream).

**Comment by techchrism** [comment]
Interesting idea. Starting/stopping a stream should be fairly easy but the metadata integration might be out of scope for this project if it's platform-specific. Can you elaborate on the integration you're looking for?

**Comment by Dycool** [comment]
u could use tracker.gg as a way to at least leave information in the stream description about the match. Tracker.gg makes a link of every match so.

**Comment by Dycool** [comment]
But tbh what I wanted was just to not keep all my games in my hard drive, instead use something like youtube where they can archive the match for you.

**Comment by techchrism** [comment]
It sounds like the metadata integration with youtube is out of scope but I may add streaming support in a future version

**Comment by techchrism** [comment]
I'm considering automated streaming out of scope for this project
