### ISSUE TITLE
Regional Fetch Errors

### ISSUE THREAD

**Issue by Dhinakar146** [techchrism/valorant-autorecord#2]
![image](https://user-images.githubusercontent.com/37206412/232659945-496a4b0e-84d6-4ada-ac76-15aa8bef76d4.png)

**Comment by techchrism** [comment]
Do you have OBS running (with the websocket enabled) before you start the application?

**Comment by Dhinakar146** [comment]
> Do you have OBS running (with the websocket enabled) before you start the application?

My bad, I was not aware that OBS WebSocket was required. I have now installed it and the program is functioning properly. However, I am currently encountering a new issue where the recording starts when I enter a game, but it crashes after a few seconds. Please refer to the screenshot that I have attached for more information.
![image](https://user-images.githubusercontent.com/37206412/236010889-27383aeb-b6c6-4b71-b188-f42b4131e6b8.png)

**Comment by Dhinakar146** [comment]
![image](https://user-images.githubusercontent.com/37206412/236012226-ffb33b96-df11-454c-a382-921d1861e2ee.png)

**Comment by techchrism** [comment]
Interesting, as far as I can tell, this is probably related to regional endpoints. I'll see if I can replicate this

**Comment by techchrism** [comment]
Sorry it took me a while to get around to this. Give the latest update a shot and let me know if the issue persists.
