### ISSUE TITLE
[Feature Request] Auto startup on OBS launch

### ISSUE THREAD

**Issue by KaIKuxy** [techchrism/valorant-autorecord#3]

**Comment by techchrism** [comment]
I think this would be best done with a shortcut to a user-created batch file that opens both OBS and valorant-autorecord.
I'll leave this open though because I should make valorant-autorecord wait for OBS to start rather than crashing immediately.

**Comment by prismillon** [comment]
just found this repo, used it for a day, it's very useful, for now I made it startup with windows but I think making it an obs plugin would be even more user friendly

**Comment by techchrism** [comment]
@prismillon I think that's generally a good idea but I still want to be able to support the use case of running OBS on a separate computer from Valorant which I think is sometimes used for streaming setups.
